-- AlterTable
ALTER TABLE `Aluno` MODIFY `dataNascimento` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Professor` MODIFY `dataNascimento` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
